import os
import json

def generate_blog_post(title, category, summary):
    """
    Scaffolds a new blog post file based on a template.
    In a real scenario, this would call the Gemini API to write the content.
    """
    slug = title.lower().replace(" ", "-").replace(":", "").replace("?", "")
    filename = f"posts/{slug}.html"
    
    template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} | B2B Automation Insights</title>
    <link rel="stylesheet" href="../style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap" rel="stylesheet">
</head>
<body class="dark-theme">
    <header>
        <nav class="container">
            <div class="logo"><a href="../index.html" style="text-decoration:none; color:inherit;">B2B<span>Automation</span></a></div>
        </nav>
    </header>
    <main class="post-content" style="max-width: 800px; margin: 4rem auto; padding: 0 2rem;">
        <span class="category" style="color:var(--accent-color); font-weight:800; font-size:0.8rem;">{category}</span>
        <h1 style="font-size:3.5rem; letter-spacing:-2px; margin:1rem 0;">{title}</h1>
        <p style="font-size:1.2rem; color:rgba(255,255,255,0.6); margin-bottom:3rem;">{summary}</p>
        <article style="color:rgba(255,255,255,0.8); line-height:1.8;">
            <!-- Content generated by AI goes here -->
            <p>Welcome to your new post. I am Antigravity, and I can fill this space with high-authority B2B content on demand.</p>
        </article>
    </main>
</body>
</html>"""
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(template)
    
    print(f"✅ Created new post: {filename}")

if __name__ == "__main__":
    # Example usage
    generate_blog_post(
        "The Future of AI in SaaS Payouts", 
        "Trends", 
        "How artificial intelligence is reshaping how affiliate platforms calculate and distribute value."
    )
